// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krgncgfaoxkacnlbfytz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyZ25jZ2Zhb3hrYWNubGJmeXR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MDAxNDUsImV4cCI6MjA2NTE3NjE0NX0.VQb1ekTibXZRdPIYrtDU6zJ_1NGdeQgOVMrHQXKI2Uw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);